"use server";

import { prisma } from "@/db";
import { dykeFull } from "@/lib/data/dyke-full";
import { imgSrc } from "@/lib/data/dyke-interiors";
import { uploadFile } from "@/lib/upload-file";
import { generateRandomString } from "@/lib/utils";

export async function dykeExteriorBootstrap() {
    // const data = dykeFull;
    // generate stepvalues
    // const data = generate();
    // return data;
    // let data = data;
    // await prisma.$transaction(async (tx) => {
    // await prisma.dykeStepValues.createMany({
    //     data: data.stepValues.filter((c) => c.id),
    // });
    // await prisma.dykeCategories.createMany({
    //     data: data.categories.filter((c) => c.id),
    // });
    // await prisma.dykeProducts.createMany({
    //     data: data.products.map((product) => {
    //         return product;
    //     }),
    // });
    // await prisma.dykeSteps.createMany({
    //     data: data.steps.map((s) => {
    //         return s;
    //     }),
    // });
    await prisma.dykeStepProducts.createMany({
        data: data.stepProducts.map((prod: any) => {
            if (!prod.uid) prod.uid = generateRandomString(5);
            return prod;
        }),
    });
    // });
}

export async function generate() {
    const data = dykeFull;
    const dbStepVals = await prisma.dykeStepValues.findMany({});
    const stepValueIdByValue: any = {};
    let currentId = 0;
    let stepValues: any[] = [];
    function getStepValueId(stepValue) {
        if (!stepValue) return null;
        let id = stepValueIdByValue[stepValue];
        if (id > 0) return id;
        ++currentId;
        stepValues.push({
            id: currentId,
            title: stepValue,
        });

        stepValueIdByValue[stepValue] = currentId;
        return currentId;
    }
    dbStepVals.map((s, i) => {
        stepValueIdByValue[s.title as any] = s.id;
        if (i == dbStepVals.length - 1) currentId = s.id;
    });
    let steps = data.steps
        .filter(
            (s) =>
                // s.value.startsWith('Exterior')
                s.id > 145
        )
        .map((step) => {
            const [root, ...rest] = step.value.split("_");
            const end = rest.pop();
            const prev = rest.pop();
            step.prevStepValueId = getStepValueId(prev);
            step.stepValueId = getStepValueId(end);
            step.rootStepValueId = getStepValueId(root);
            return step;
        });
    const stepProducts = data.stepProducts
        .filter((p) => steps.some((s) => s.id == p.stepId))
        .map((p) => {
            return {
                id: p.id,
                dykeStepId: p.stepId,
                dykeProductId: p.productId,
            };
        });
    const categories = data.categories.filter((s) => s.id > 20);
    const dbProds = await prisma.dykeProducts.findMany({});
    const products = await Promise.all(
        data.products
            .filter((pr) => dbProds.every((p) => p.id != pr.id))
            .map(async (prod) => {
                let src = prod.img || "";
                Object.entries(imgSrc).map(([k, v]) => {
                    src = src.replace(`${k}/`, `${v}/`);
                });
                if (src) {
                    const u = await uploadFile(src, "dyke");
                    if (u && u.secure_url)
                        prod.img = u.secure_url.split("dyke/")[1];
                }
                return prod;
            })
    );
    return { steps, stepValues, categories, stepProducts, products };
}
const data = {
    steps: [
        {
            id: 146,
            title: "Casing Y/N",
            value: 'Interior_Interior Door Unit - Single 1-3/4"_width_height_hand_bore_door type_door_jamb size_jamb species_jamb type_--jamb stop_rip jamb_hinge finish_hinge type',
            prevStepValueId: 25,
            stepValueId: 35,
            rootStepValueId: 1,
        },
        {
            id: 147,
            title: "Door Configuration",
            value: "Exterior",
            prevStepValueId: null,
            stepValueId: null,
            rootStepValueId: 36,
        },
        {
            id: 148,
            title: "Single Unit Type",
            value: "Exterior_Exterior Door Unit - Single",
            prevStepValueId: null,
            stepValueId: 37,
            rootStepValueId: 36,
        },
        {
            id: 149,
            title: "Double Unit Type",
            value: "Exterior_Exterior Door Unit - Double",
            prevStepValueId: null,
            stepValueId: 38,
            rootStepValueId: 36,
        },
        {
            id: 150,
            title: "Width",
            value: "Exterior_Exterior Door Slab (Prepped)",
            prevStepValueId: null,
            stepValueId: 39,
            rootStepValueId: 36,
        },
        {
            id: 151,
            title: "Single Unit Type",
            value: "Exterior_Exterior Frame Only - Single",
            prevStepValueId: null,
            stepValueId: 40,
            rootStepValueId: 36,
        },
        {
            id: 152,
            title: "Width",
            value: "Exterior_Exterior Frame Only - Double_double unit type",
            prevStepValueId: 41,
            stepValueId: 42,
            rootStepValueId: 36,
        },
        {
            id: 153,
            title: "Width",
            value: "Exterior_Exterior Door Unit - Double_double unit type",
            prevStepValueId: 38,
            stepValueId: 42,
            rootStepValueId: 36,
        },
        {
            id: 154,
            title: "Double Unit Type",
            value: "Exterior_Exterior Frame Only - Double",
            prevStepValueId: null,
            stepValueId: 41,
            rootStepValueId: 36,
        },
        {
            id: 155,
            title: "Width",
            value: "Exterior_Exterior Split Metal Frame Door Unit - Single",
            prevStepValueId: null,
            stepValueId: 43,
            rootStepValueId: 36,
        },
        {
            id: 156,
            title: "Height",
            value: "Exterior_Exterior Split Metal Frame Door Unit - Single_width",
            prevStepValueId: 43,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 157,
            title: "Height",
            value: "Exterior_Exterior Door Slab (Prepped)_width",
            prevStepValueId: 39,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 158,
            title: "Height",
            value: "Exterior_Exterior Frame Only - Double_double unit type_width",
            prevStepValueId: 42,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 159,
            title: "Height",
            value: "Exterior_Exterior Door Unit - Double_double unit type_width",
            prevStepValueId: 42,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 160,
            title: "Width",
            value: "Exterior_Exterior Door Unit - Single_Sidelight Only",
            prevStepValueId: 37,
            stepValueId: 44,
            rootStepValueId: 36,
        },
        {
            id: 161,
            value: "Exterior_Exterior Door Unit - Single_Sidelight Only_width",
            prevStepValueId: 44,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 162,
            title: "Width",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight",
            prevStepValueId: 37,
            stepValueId: 45,
            rootStepValueId: 36,
        },
        {
            id: 163,
            title: "Height",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width",
            prevStepValueId: 45,
            stepValueId: 12,
            rootStepValueId: 36,
        },
        {
            id: 164,
            title: "Hand",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height",
            prevStepValueId: 12,
            stepValueId: 13,
            rootStepValueId: 36,
        },
        {
            id: 165,
            title: "Hand",
            value: "Exterior_Exterior Split Metal Frame Door Unit - Single_width_height",
            prevStepValueId: 12,
            stepValueId: 13,
            rootStepValueId: 36,
        },
        {
            id: 166,
            title: "Hand",
            value: "Exterior_Exterior Door Slab (Prepped)_width_height",
            prevStepValueId: 12,
            stepValueId: 13,
            rootStepValueId: 36,
        },
        {
            id: 167,
            title: "Hand",
            value: "Exterior_Exterior Frame Only - Double_double unit type_width_height",
            prevStepValueId: 12,
            stepValueId: 13,
            rootStepValueId: 36,
        },
        {
            id: 168,
            title: "Hand",
            value: "Exterior_Exterior Door Unit - Double_double unit type_width_height",
            prevStepValueId: 12,
            stepValueId: 13,
            rootStepValueId: 36,
        },
        {
            id: 169,
            title: "Swing",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand",
            prevStepValueId: 13,
            stepValueId: 15,
            rootStepValueId: 36,
        },
        {
            id: 170,
            title: "Swing",
            value: "Exterior_Exterior Split Metal Frame Door Unit - Single_width_height_hand",
            prevStepValueId: 13,
            stepValueId: 15,
            rootStepValueId: 36,
        },
        {
            id: 171,
            title: "Swing",
            value: "Exterior_Exterior Door Slab (Prepped)_width_height_hand",
            prevStepValueId: 13,
            stepValueId: 15,
            rootStepValueId: 36,
        },
        {
            id: 172,
            title: "Swing",
            value: "Exterior_Exterior Frame Only - Double_double unit type_width_height_hand",
            prevStepValueId: 13,
            stepValueId: 15,
            rootStepValueId: 36,
        },
        {
            id: 173,
            title: "Swing",
            value: "Exterior_Exterior Door Unit - Double_double unit type_width_height_hand",
            prevStepValueId: 13,
            stepValueId: 15,
            rootStepValueId: 36,
        },
        {
            id: 174,
            title: "Bore",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing",
            prevStepValueId: 15,
            stepValueId: 46,
            rootStepValueId: 36,
        },
        {
            id: 175,
            title: "Door With/Without Glass?",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore",
            prevStepValueId: 46,
            stepValueId: 16,
            rootStepValueId: 36,
        },
        {
            id: 176,
            title: "Door View",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass",
            prevStepValueId: 16,
            stepValueId: 47,
            rootStepValueId: 36,
        },
        {
            id: 177,
            title: "Door View",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass",
            prevStepValueId: 16,
            stepValueId: 48,
            rootStepValueId: 36,
        },
        {
            id: 178,
            title: "Door Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view",
            prevStepValueId: 47,
            stepValueId: 49,
            rootStepValueId: 36,
        },
        {
            id: 179,
            title: "Door Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass_door view",
            prevStepValueId: 48,
            stepValueId: 49,
            rootStepValueId: 36,
        },
        {
            id: 180,
            title: "Door Species",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type",
            prevStepValueId: 49,
            stepValueId: 17,
            rootStepValueId: 36,
        },
        {
            id: 181,
            title: "Door Species",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass_door view_door type",
            prevStepValueId: 49,
            stepValueId: 17,
            rootStepValueId: 36,
        },
        {
            id: 182,
            title: "Impact Door",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species",
            prevStepValueId: 17,
            stepValueId: 50,
            rootStepValueId: 36,
        },
        {
            id: 183,
            title: "Impact Door",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass_door view_door type_door species",
            prevStepValueId: 17,
            stepValueId: 50,
            rootStepValueId: 36,
        },
        {
            id: 184,
            title: "Door",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door",
            prevStepValueId: 50,
            stepValueId: 51,
            rootStepValueId: 36,
        },
        {
            id: 185,
            title: "Door",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass_door view_door type_door species_impact door",
            prevStepValueId: 50,
            stepValueId: 51,
            rootStepValueId: 36,
        },
        {
            id: 186,
            title: "Glass Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door",
            prevStepValueId: 51,
            stepValueId: 18,
            rootStepValueId: 36,
        },
        {
            id: 187,
            title: "Glass Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Panel Door No Glass_door view_door type_door species_impact door_door",
            prevStepValueId: 51,
            stepValueId: 18,
            rootStepValueId: 36,
        },
        {
            id: 188,
            title: "Impact Glass",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass",
            prevStepValueId: 18,
            stepValueId: 52,
            rootStepValueId: 36,
        },
        {
            id: 189,
            title: "Insert/Open Cutout",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass",
            prevStepValueId: 52,
            stepValueId: 53,
            rootStepValueId: 36,
        },
        {
            id: 190,
            title: "--Insert",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout",
            prevStepValueId: 53,
            stepValueId: 54,
            rootStepValueId: 36,
        },
        {
            id: 191,
            title: "Custom SDL",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT",
            prevStepValueId: 54,
            stepValueId: 55,
            rootStepValueId: 36,
        },
        {
            id: 192,
            title: "Sidelight Width",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL",
            prevStepValueId: 55,
            stepValueId: 56,
            rootStepValueId: 36,
        },
        {
            id: 193,
            title: "Jamb Depth",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width",
            prevStepValueId: 56,
            stepValueId: 57,
            rootStepValueId: 36,
        },
        {
            id: 194,
            title: "Sill Finish",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth",
            prevStepValueId: 57,
            stepValueId: 58,
            rootStepValueId: 36,
        },
        {
            id: 195,
            title: "Sill Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish",
            prevStepValueId: 58,
            stepValueId: 59,
            rootStepValueId: 36,
        },
        {
            id: 196,
            title: "Jamb Species",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type",
            prevStepValueId: 59,
            stepValueId: 60,
            rootStepValueId: 36,
        },
        {
            id: 197,
            title: "Jamb Species",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_No Sill",
            prevStepValueId: 58,
            stepValueId: 61,
            rootStepValueId: 36,
        },
        {
            id: 198,
            title: "--Jamb Leg",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species",
            prevStepValueId: 60,
            stepValueId: 20,
            rootStepValueId: 36,
        },
        {
            id: 199,
            title: "--Jamb Leg",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_No Sill_jamb species",
            prevStepValueId: 61,
            stepValueId: 20,
            rootStepValueId: 36,
        },
        {
            id: 200,
            title: "Rip Jamb",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB",
            prevStepValueId: 20,
            stepValueId: 62,
            rootStepValueId: 36,
        },
        {
            id: 201,
            title: "Weatherstrip Color",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb",
            prevStepValueId: 62,
            stepValueId: 24,
            rootStepValueId: 36,
        },
        {
            id: 202,
            title: "Hinge Type",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color",
            prevStepValueId: 24,
            stepValueId: 63,
            rootStepValueId: 36,
        },
        {
            id: 203,
            title: "Hinge Finish",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type",
            prevStepValueId: 63,
            stepValueId: 35,
            rootStepValueId: 36,
        },
        {
            id: 204,
            title: "Exterior Trim Species",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish",
            prevStepValueId: 35,
            stepValueId: 25,
            rootStepValueId: 36,
        },
        {
            id: 205,
            title: "Exterior Trim Leg",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim",
            prevStepValueId: 25,
            stepValueId: 64,
            rootStepValueId: 36,
        },
        {
            id: 206,
            title: "Exterior Trim Head",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim_exterior trim leg",
            prevStepValueId: 64,
            stepValueId: 65,
            rootStepValueId: 36,
        },
        {
            id: 207,
            title: "Cutdown Height",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim_exterior trim leg_exterior trim head",
            prevStepValueId: 65,
            stepValueId: 66,
            rootStepValueId: 36,
        },
        {
            id: 208,
            title: "Cutdown Width",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim_exterior trim leg_exterior trim head_cutdown height",
            prevStepValueId: 66,
            stepValueId: 27,
            rootStepValueId: 36,
        },
        {
            id: 209,
            title: "Fire Label (Door)",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim_exterior trim leg_exterior trim head_cutdown height_cutdown width",
            prevStepValueId: 27,
            stepValueId: 67,
            rootStepValueId: 36,
        },
        {
            id: 210,
            title: "Fire Label (Jamb)",
            value: "Exterior_Exterior Door Unit - Single_No Sidelight_width_height_hand_Inswing_bore_Door w/Glass_door view_door type_door species_impact door_door_Clear Glass_impact glass_insert/open cutout_1464 1LT IG IMP WHITE FLAT FRM INSERT_Shop Applied Custom SDL_sidelight width_jamb depth_Mill Finish_sill type_jamb species_PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB_rip jamb_weatherstrip color_hinge type_hinge finish_Primed Exterior Trim_exterior trim leg_exterior trim head_cutdown height_cutdown width_fire label (door)",
            prevStepValueId: 67,
            stepValueId: 68,
            rootStepValueId: 36,
        },
    ],
    stepValues: [
        {
            id: 35,
            title: "hinge type",
        },
        {
            id: 36,
            title: "Exterior",
        },
        {
            id: 37,
            title: "Exterior Door Unit - Single",
        },
        {
            id: 38,
            title: "Exterior Door Unit - Double",
        },
        {
            id: 39,
            title: "Exterior Door Slab (Prepped)",
        },
        {
            id: 40,
            title: "Exterior Frame Only - Single",
        },
        {
            id: 41,
            title: "Exterior Frame Only - Double",
        },
        {
            id: 42,
            title: "double unit type",
        },
        {
            id: 43,
            title: "Exterior Split Metal Frame Door Unit - Single",
        },
        {
            id: 44,
            title: "Sidelight Only",
        },
        {
            id: 45,
            title: "No Sidelight",
        },
        {
            id: 46,
            title: "Inswing",
        },
        {
            id: 47,
            title: "Door w/Glass",
        },
        {
            id: 48,
            title: "Panel Door No Glass",
        },
        {
            id: 49,
            title: "door view",
        },
        {
            id: 50,
            title: "door species",
        },
        {
            id: 51,
            title: "impact door",
        },
        {
            id: 52,
            title: "Clear Glass",
        },
        {
            id: 53,
            title: "impact glass",
        },
        {
            id: 54,
            title: "insert/open cutout",
        },
        {
            id: 55,
            title: "1464 1LT IG IMP WHITE FLAT FRM INSERT",
        },
        {
            id: 56,
            title: "Shop Applied Custom SDL",
        },
        {
            id: 57,
            title: "sidelight width",
        },
        {
            id: 58,
            title: "jamb depth",
        },
        {
            id: 59,
            title: "Mill Finish",
        },
        {
            id: 60,
            title: "sill type",
        },
        {
            id: 61,
            title: "No Sill",
        },
        {
            id: 62,
            title: "PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB",
        },
        {
            id: 63,
            title: "weatherstrip color",
        },
        {
            id: 64,
            title: "Primed Exterior Trim",
        },
        {
            id: 65,
            title: "exterior trim leg",
        },
        {
            id: 66,
            title: "exterior trim head",
        },
        {
            id: 67,
            title: "cutdown width",
        },
        {
            id: 68,
            title: "fire label (door)",
        },
    ],
    categories: [
        {
            id: 21,
            title: "Hinge Type",
        },
        {
            id: 22,
            title: "Single Unit Type",
        },
        {
            id: 23,
            title: "Double Unit Type",
        },
        {
            id: 24,
            title: "Swing",
        },
        {
            id: 25,
            title: "Door With/Without Glass?",
        },
        {
            id: 26,
            title: "Door View",
        },
        {
            id: 27,
            title: "Door Species",
        },
        {
            id: 28,
            title: "Impact Door",
        },
        {
            id: 29,
            title: "Glass Type",
        },
        {
            id: 30,
            title: "Impact Glass",
        },
        {
            id: 31,
            title: "Insert/Open Cutout",
        },
        {
            id: 32,
            title: "--Insert",
        },
        {
            id: 33,
            title: "Custom SDL",
        },
        {
            id: 34,
            title: "Sidelight Width",
        },
        {
            id: 35,
            title: "Jamb Depth",
        },
        {
            id: 36,
            title: "Sill Finish",
        },
        {
            id: 37,
            title: "Sill Type",
        },
        {
            id: 38,
            title: "--Jamb Leg",
        },
        {
            id: 39,
            title: "Weatherstrip Color",
        },
        {
            id: 40,
            title: "Exterior Trim Species",
        },
        {
            id: 41,
            title: "Exterior Trim Leg",
        },
        {
            id: 42,
            title: "Exterior Trim Head",
        },
        {
            id: 43,
            title: "Cutdown Width",
        },
        {
            id: 44,
            title: "Fire Label (Door)",
        },
        {
            id: 45,
            title: "Fire Label (Jamb)",
        },
    ],
    stepProducts: [
        {
            dykeProductId: 210,
            dykeStepId: 130,
            id: 684,
        },
        {
            id: 685,
            dykeStepId: 146,
            dykeProductId: 211,
        },
        {
            id: 686,
            dykeStepId: 146,
            dykeProductId: 212,
        },
        {
            id: 687,
            dykeStepId: 147,
            dykeProductId: 213,
        },
        {
            id: 688,
            dykeStepId: 147,
            dykeProductId: 214,
        },
        {
            id: 689,
            dykeStepId: 147,
            dykeProductId: 215,
        },
        {
            id: 690,
            dykeStepId: 147,
            dykeProductId: 216,
        },
        {
            id: 691,
            dykeStepId: 147,
            dykeProductId: 217,
        },
        {
            id: 692,
            dykeStepId: 147,
            dykeProductId: 218,
        },
        {
            id: 693,
            dykeStepId: 148,
            dykeProductId: 219,
        },
        {
            id: 694,
            dykeStepId: 148,
            dykeProductId: 220,
        },
        {
            id: 695,
            dykeStepId: 149,
            dykeProductId: 221,
        },
        {
            id: 696,
            dykeStepId: 150,
            dykeProductId: 222,
        },
        {
            id: 697,
            dykeStepId: 150,
            dykeProductId: 223,
        },
        {
            id: 698,
            dykeStepId: 150,
            dykeProductId: 224,
        },
        {
            id: 699,
            dykeStepId: 150,
            dykeProductId: 225,
        },
        {
            id: 700,
            dykeStepId: 150,
            dykeProductId: 226,
        },
        {
            id: 701,
            dykeStepId: 150,
            dykeProductId: 227,
        },
        {
            id: 702,
            dykeStepId: 151,
            dykeProductId: 228,
        },
        {
            id: 703,
            dykeStepId: 151,
            dykeProductId: 229,
        },
        {
            id: 704,
            dykeStepId: 152,
            dykeProductId: 230,
        },
        {
            id: 705,
            dykeStepId: 152,
            dykeProductId: 231,
        },
        {
            id: 706,
            dykeStepId: 152,
            dykeProductId: 232,
        },
        {
            id: 707,
            dykeStepId: 152,
            dykeProductId: 233,
        },
        {
            id: 708,
            dykeStepId: 152,
            dykeProductId: 234,
        },
        {
            id: 709,
            dykeStepId: 152,
            dykeProductId: 235,
        },
        {
            id: 710,
            dykeStepId: 153,
            dykeProductId: 230,
        },
        {
            id: 711,
            dykeStepId: 153,
            dykeProductId: 231,
        },
        {
            id: 712,
            dykeStepId: 153,
            dykeProductId: 232,
        },
        {
            id: 713,
            dykeStepId: 153,
            dykeProductId: 233,
        },
        {
            id: 714,
            dykeStepId: 153,
            dykeProductId: 234,
        },
        {
            id: 715,
            dykeStepId: 153,
            dykeProductId: 235,
        },
        {
            id: 716,
            dykeStepId: 154,
            dykeProductId: 236,
        },
        {
            id: 717,
            dykeStepId: 152,
            dykeProductId: 230,
        },
        {
            id: 718,
            dykeStepId: 152,
            dykeProductId: 231,
        },
        {
            id: 719,
            dykeStepId: 152,
            dykeProductId: 232,
        },
        {
            id: 720,
            dykeStepId: 152,
            dykeProductId: 233,
        },
        {
            id: 721,
            dykeStepId: 152,
            dykeProductId: 234,
        },
        {
            id: 722,
            dykeStepId: 152,
            dykeProductId: 235,
        },
        {
            id: 723,
            dykeStepId: 155,
            dykeProductId: 237,
        },
        {
            id: 724,
            dykeStepId: 156,
            dykeProductId: 238,
        },
        {
            id: 725,
            dykeStepId: 156,
            dykeProductId: 239,
        },
        {
            id: 726,
            dykeStepId: 157,
            dykeProductId: 238,
        },
        {
            id: 727,
            dykeStepId: 157,
            dykeProductId: 239,
        },
        {
            id: 728,
            dykeStepId: 158,
            dykeProductId: 238,
        },
        {
            id: 729,
            dykeStepId: 158,
            dykeProductId: 239,
        },
        {
            id: 730,
            dykeStepId: 159,
            dykeProductId: 238,
        },
        {
            id: 731,
            dykeStepId: 159,
            dykeProductId: 239,
        },
        {
            id: 732,
            dykeStepId: 160,
            dykeProductId: 240,
        },
        {
            id: 733,
            dykeStepId: 160,
            dykeProductId: 241,
        },
        {
            id: 734,
            dykeStepId: 160,
            dykeProductId: 242,
        },
        {
            id: 735,
            dykeStepId: 162,
            dykeProductId: 243,
        },
        {
            id: 736,
            dykeStepId: 162,
            dykeProductId: 244,
        },
        {
            id: 737,
            dykeStepId: 162,
            dykeProductId: 245,
        },
        {
            id: 738,
            dykeStepId: 162,
            dykeProductId: 246,
        },
        {
            id: 739,
            dykeStepId: 162,
            dykeProductId: 247,
        },
        {
            id: 740,
            dykeStepId: 162,
            dykeProductId: 248,
        },
        {
            id: 741,
            dykeStepId: 162,
            dykeProductId: 241,
        },
        {
            id: 742,
            dykeStepId: 162,
            dykeProductId: 242,
        },
        {
            id: 743,
            dykeStepId: 163,
            dykeProductId: 249,
        },
        {
            id: 744,
            dykeStepId: 163,
            dykeProductId: 250,
        },
        {
            id: 745,
            dykeStepId: 163,
            dykeProductId: 251,
        },
        {
            id: 746,
            dykeStepId: 161,
            dykeProductId: 249,
        },
        {
            id: 747,
            dykeStepId: 161,
            dykeProductId: 250,
        },
        {
            id: 748,
            dykeStepId: 161,
            dykeProductId: 251,
        },
        {
            id: 749,
            dykeStepId: 164,
            dykeProductId: 252,
        },
        {
            id: 750,
            dykeStepId: 164,
            dykeProductId: 253,
        },
        {
            id: 751,
            dykeStepId: 164,
            dykeProductId: 254,
        },
        {
            id: 752,
            dykeStepId: 165,
            dykeProductId: 252,
        },
        {
            id: 753,
            dykeStepId: 165,
            dykeProductId: 253,
        },
        {
            id: 754,
            dykeStepId: 165,
            dykeProductId: 254,
        },
        {
            id: 755,
            dykeStepId: 166,
            dykeProductId: 252,
        },
        {
            id: 756,
            dykeStepId: 166,
            dykeProductId: 253,
        },
        {
            id: 757,
            dykeStepId: 166,
            dykeProductId: 254,
        },
        {
            id: 758,
            dykeStepId: 167,
            dykeProductId: 252,
        },
        {
            id: 759,
            dykeStepId: 167,
            dykeProductId: 253,
        },
        {
            id: 760,
            dykeStepId: 167,
            dykeProductId: 254,
        },
        {
            id: 761,
            dykeStepId: 168,
            dykeProductId: 252,
        },
        {
            id: 762,
            dykeStepId: 168,
            dykeProductId: 253,
        },
        {
            id: 763,
            dykeStepId: 168,
            dykeProductId: 254,
        },
        {
            id: 764,
            dykeStepId: 169,
            dykeProductId: 255,
        },
        {
            id: 765,
            dykeStepId: 169,
            dykeProductId: 256,
        },
        {
            id: 766,
            dykeStepId: 170,
            dykeProductId: 255,
        },
        {
            id: 767,
            dykeStepId: 170,
            dykeProductId: 256,
        },
        {
            id: 768,
            dykeStepId: 171,
            dykeProductId: 255,
        },
        {
            id: 769,
            dykeStepId: 171,
            dykeProductId: 256,
        },
        {
            id: 770,
            dykeStepId: 172,
            dykeProductId: 255,
        },
        {
            id: 771,
            dykeStepId: 172,
            dykeProductId: 256,
        },
        {
            id: 772,
            dykeStepId: 173,
            dykeProductId: 255,
        },
        {
            id: 773,
            dykeStepId: 173,
            dykeProductId: 256,
        },
        {
            id: 774,
            dykeStepId: 174,
            dykeProductId: 257,
        },
        {
            id: 775,
            dykeStepId: 174,
            dykeProductId: 258,
        },
        {
            id: 776,
            dykeStepId: 174,
            dykeProductId: 259,
        },
        {
            id: 777,
            dykeStepId: 175,
            dykeProductId: 260,
        },
        {
            id: 778,
            dykeStepId: 175,
            dykeProductId: 261,
        },
        {
            id: 779,
            dykeStepId: 175,
            dykeProductId: 262,
        },
        {
            id: 780,
            dykeStepId: 176,
            dykeProductId: 263,
        },
        {
            id: 781,
            dykeStepId: 176,
            dykeProductId: 264,
        },
        {
            id: 782,
            dykeStepId: 176,
            dykeProductId: 265,
        },
        {
            id: 783,
            dykeStepId: 176,
            dykeProductId: 266,
        },
        {
            id: 784,
            dykeStepId: 176,
            dykeProductId: 267,
        },
        {
            id: 785,
            dykeStepId: 177,
            dykeProductId: 268,
        },
        {
            id: 786,
            dykeStepId: 176,
            dykeProductId: 269,
        },
        {
            id: 787,
            dykeStepId: 176,
            dykeProductId: 264,
        },
        {
            id: 788,
            dykeStepId: 176,
            dykeProductId: 265,
        },
        {
            id: 789,
            dykeStepId: 176,
            dykeProductId: 266,
        },
        {
            id: 790,
            dykeStepId: 176,
            dykeProductId: 267,
        },
        {
            id: 791,
            dykeStepId: 178,
            dykeProductId: 270,
        },
        {
            id: 792,
            dykeStepId: 178,
            dykeProductId: 271,
        },
        {
            id: 793,
            dykeStepId: 179,
            dykeProductId: 270,
        },
        {
            id: 794,
            dykeStepId: 179,
            dykeProductId: 271,
        },
        {
            id: 795,
            dykeStepId: 178,
            dykeProductId: 270,
        },
        {
            id: 796,
            dykeStepId: 178,
            dykeProductId: 271,
        },
        {
            id: 797,
            dykeStepId: 180,
            dykeProductId: 272,
        },
        {
            id: 798,
            dykeStepId: 181,
            dykeProductId: 272,
        },
        {
            id: 799,
            dykeStepId: 182,
            dykeProductId: 273,
        },
        {
            id: 800,
            dykeStepId: 183,
            dykeProductId: 273,
        },
        {
            id: 801,
            dykeStepId: 184,
            dykeProductId: 274,
        },
        {
            id: 802,
            dykeStepId: 185,
            dykeProductId: 274,
        },
        {
            id: 803,
            dykeStepId: 186,
            dykeProductId: 275,
        },
        {
            id: 804,
            dykeStepId: 186,
            dykeProductId: 276,
        },
        {
            id: 805,
            dykeStepId: 186,
            dykeProductId: 277,
        },
        {
            id: 806,
            dykeStepId: 186,
            dykeProductId: 278,
        },
        {
            id: 807,
            dykeStepId: 186,
            dykeProductId: 279,
        },
        {
            id: 808,
            dykeStepId: 187,
            dykeProductId: 275,
        },
        {
            id: 809,
            dykeStepId: 187,
            dykeProductId: 276,
        },
        {
            id: 810,
            dykeStepId: 187,
            dykeProductId: 277,
        },
        {
            id: 811,
            dykeStepId: 187,
            dykeProductId: 278,
        },
        {
            id: 812,
            dykeStepId: 187,
            dykeProductId: 279,
        },
        {
            id: 813,
            dykeStepId: 186,
            dykeProductId: 280,
        },
        {
            id: 814,
            dykeStepId: 186,
            dykeProductId: 276,
        },
        {
            id: 815,
            dykeStepId: 186,
            dykeProductId: 277,
        },
        {
            id: 816,
            dykeStepId: 186,
            dykeProductId: 278,
        },
        {
            id: 817,
            dykeStepId: 186,
            dykeProductId: 279,
        },
        {
            id: 818,
            dykeStepId: 188,
            dykeProductId: 281,
        },
        {
            id: 819,
            dykeStepId: 189,
            dykeProductId: 282,
        },
        {
            id: 820,
            dykeStepId: 190,
            dykeProductId: 283,
        },
        {
            id: 821,
            dykeStepId: 190,
            dykeProductId: 284,
        },
        {
            id: 822,
            dykeStepId: 190,
            dykeProductId: 285,
        },
        {
            id: 823,
            dykeStepId: 191,
            dykeProductId: 286,
        },
        {
            id: 824,
            dykeStepId: 191,
            dykeProductId: 287,
        },
        {
            id: 825,
            dykeStepId: 192,
            dykeProductId: 288,
        },
        {
            id: 826,
            dykeStepId: 193,
            dykeProductId: 289,
        },
        {
            id: 827,
            dykeStepId: 193,
            dykeProductId: 290,
        },
        {
            id: 828,
            dykeStepId: 193,
            dykeProductId: 291,
        },
        {
            id: 829,
            dykeStepId: 193,
            dykeProductId: 292,
        },
        {
            id: 830,
            dykeStepId: 193,
            dykeProductId: 293,
        },
        {
            id: 831,
            dykeStepId: 193,
            dykeProductId: 294,
        },
        {
            id: 832,
            dykeStepId: 194,
            dykeProductId: 295,
        },
        {
            id: 833,
            dykeStepId: 194,
            dykeProductId: 296,
        },
        {
            id: 834,
            dykeStepId: 195,
            dykeProductId: 297,
        },
        {
            id: 835,
            dykeStepId: 196,
            dykeProductId: 298,
        },
        {
            id: 836,
            dykeStepId: 196,
            dykeProductId: 299,
        },
        {
            id: 837,
            dykeStepId: 196,
            dykeProductId: 300,
        },
        {
            id: 838,
            dykeStepId: 196,
            dykeProductId: 301,
        },
        {
            id: 839,
            dykeStepId: 197,
            dykeProductId: 298,
        },
        {
            id: 840,
            dykeStepId: 197,
            dykeProductId: 299,
        },
        {
            id: 841,
            dykeStepId: 197,
            dykeProductId: 300,
        },
        {
            id: 842,
            dykeStepId: 197,
            dykeProductId: 301,
        },
        {
            id: 843,
            dykeStepId: 196,
            dykeProductId: 298,
        },
        {
            id: 844,
            dykeStepId: 196,
            dykeProductId: 299,
        },
        {
            id: 845,
            dykeStepId: 196,
            dykeProductId: 300,
        },
        {
            id: 846,
            dykeStepId: 196,
            dykeProductId: 301,
        },
        {
            id: 847,
            dykeStepId: 198,
            dykeProductId: 302,
        },
        {
            id: 848,
            dykeStepId: 198,
            dykeProductId: 303,
        },
        {
            id: 849,
            dykeStepId: 199,
            dykeProductId: 302,
        },
        {
            id: 850,
            dykeStepId: 199,
            dykeProductId: 303,
        },
        {
            id: 851,
            dykeStepId: 200,
            dykeProductId: 304,
        },
        {
            id: 852,
            dykeStepId: 200,
            dykeProductId: 305,
        },
        {
            id: 853,
            dykeStepId: 201,
            dykeProductId: 306,
        },
        {
            id: 854,
            dykeStepId: 201,
            dykeProductId: 307,
        },
        {
            id: 855,
            dykeStepId: 202,
            dykeProductId: 308,
        },
        {
            id: 856,
            dykeStepId: 202,
            dykeProductId: 309,
        },
        {
            id: 857,
            dykeStepId: 202,
            dykeProductId: 310,
        },
        {
            id: 858,
            dykeStepId: 203,
            dykeProductId: 311,
        },
        {
            id: 859,
            dykeStepId: 203,
            dykeProductId: 312,
        },
        {
            id: 860,
            dykeStepId: 203,
            dykeProductId: 313,
        },
        {
            id: 861,
            dykeStepId: 203,
            dykeProductId: 314,
        },
        {
            id: 862,
            dykeStepId: 203,
            dykeProductId: 315,
        },
        {
            id: 863,
            dykeStepId: 203,
            dykeProductId: 316,
        },
        {
            id: 864,
            dykeStepId: 203,
            dykeProductId: 317,
        },
        {
            id: 865,
            dykeStepId: 203,
            dykeProductId: 318,
        },
        {
            id: 866,
            dykeStepId: 203,
            dykeProductId: 319,
        },
        {
            id: 867,
            dykeStepId: 204,
            dykeProductId: 320,
        },
        {
            id: 868,
            dykeStepId: 204,
            dykeProductId: 321,
        },
        {
            id: 869,
            dykeStepId: 204,
            dykeProductId: 322,
        },
        {
            id: 870,
            dykeStepId: 204,
            dykeProductId: 323,
        },
        {
            id: 871,
            dykeStepId: 205,
            dykeProductId: 324,
        },
        {
            id: 872,
            dykeStepId: 206,
            dykeProductId: 324,
        },
        {
            id: 873,
            dykeStepId: 207,
            dykeProductId: 325,
        },
        {
            id: 874,
            dykeStepId: 208,
            dykeProductId: 326,
        },
        {
            id: 875,
            dykeStepId: 208,
            dykeProductId: 327,
        },
        {
            id: 876,
            dykeStepId: 209,
            dykeProductId: 328,
        },
        {
            id: 877,
            dykeStepId: 210,
            dykeProductId: 329,
        },
    ],
    products: [
        {
            img: "ifk8eeymfliwezyv0iah.jpg",
            noteRequired: false,
            description: "",
            title: "Spring Hinges",
            price: null,
            value: "SPR",
            productCode: "XDUS32-HINGETYPE10",
            qty: 1,
            meta: {},
            categoryId: 21,
            id: 210,
        },
        {
            img: "e1frvpc5mijzb97g7tro.jpg",
            noteRequired: false,
            description: "",
            title: "Casing Same Both Sides",
            price: null,
            value: "SM",
            productCode: "XDUS32-CSGSIDES05",
            qty: 1,
            meta: {},
            categoryId: 15,
            id: 211,
        },
        {
            img: "opx0ifqudaoen0ikzwnk.jpg",
            noteRequired: false,
            description: "NO CASING,",
            title: "No Casing",
            price: null,
            value: "NONE",
            productCode: "XDUS32-CSGSIDES15",
            qty: 1,
            meta: {},
            categoryId: 15,
            id: 212,
        },
        {
            img: "k8dcj7ekcyhzggpelw57.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Door Unit - Single",
            price: null,
            value: "Exterior Door Unit - Single",
            productCode: "KIT32/15-EDUS",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 213,
        },
        {
            img: "bzyemewbmfhhd2tofijw.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Door Unit - Double",
            price: null,
            value: "Exterior Door Unit - Double",
            productCode: "KIT32/16-EDUD",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 214,
        },
        {
            img: "hp7ycmdfj69s6erubwh3.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Door Slab (Prepped)",
            price: null,
            value: "Exterior Door Slab (Prepped)",
            productCode: "KIT32/18-EDO",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 215,
        },
        {
            img: "fsx0zwalv1hgj5tfg8zm.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Frame Only - Single",
            price: null,
            value: "Exterior Frame Only - Single",
            productCode: "KIT32/19-EFOS",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 216,
        },
        {
            img: "hnsh7jjfi0zq4rmgra9t.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Frame Only - Double",
            price: null,
            value: "Exterior Frame Only - Double",
            productCode: "KIT32/20-EFOD",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 217,
        },
        {
            img: "zjyjnrkdy8fvgbc6bbfz.jpg",
            noteRequired: false,
            description: null,
            title: "Exterior Split Metal Frame Door Unit - Single",
            price: null,
            value: "Exterior Split Metal Frame Door Unit - Single",
            productCode: "KIT32/21-EMFS",
            qty: 0,
            meta: {},
            categoryId: 2,
            id: 218,
        },
        {
            img: "iifjiypgzbkhxvguz4ws.jpg",
            noteRequired: false,
            description: "",
            title: "No Sidelight",
            price: null,
            value: "SGL",
            productCode: "EDUS32-SGLTYPE005",
            qty: 1,
            meta: {},
            id: 219,
        },
        {
            img: "eeeif1vpks37a0a1ozdq.jpg",
            noteRequired: false,
            description: "Sidelight Only",
            title: "Sidelight Only",
            price: null,
            value: "SDLT",
            productCode: "EDUS32-SGLTYPE010",
            qty: 1,
            meta: {},
            categoryId: 22,
            id: 220,
        },
        {
            img: "ob2kkhfhtf8phwjoozcf.jpg",
            noteRequired: false,
            description: "Double Active",
            title: "Double Active",
            price: null,
            value: "ADBL",
            productCode: "EDUD32-DBLTYPE005",
            qty: 1,
            meta: {},
            id: 221,
        },
        {
            img: "r0phloffc2vn4gd8f3g4.jpg",
            noteRequired: false,
            description: "3-0",
            title: "3-0",
            price: null,
            value: "30",
            productCode: "EDO32-WIDTH005",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 222,
        },
        {
            img: "ucyksf2ek0idnutv9ra6.jpg",
            noteRequired: false,
            description: "2-10",
            title: "2-10",
            price: null,
            value: "29",
            productCode: "EDO32-WIDTH010",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 223,
        },
        {
            img: "ktmq4qeajwqgnpvbtt3m.jpg",
            noteRequired: false,
            description: "2-8",
            title: "2-8",
            price: null,
            value: "28",
            productCode: "EDO32-WIDTH015",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 224,
        },
        {
            img: "v55cvt73wyxgtlmy39mh.jpg",
            noteRequired: false,
            description: "2-6",
            title: "2-6",
            price: null,
            value: "26",
            productCode: "EDO32-WIDTH020",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 225,
        },
        {
            img: "qtxszg4tai0m76b3q1gv.jpg",
            noteRequired: false,
            description: "2-4",
            title: "2-4",
            price: null,
            value: "24",
            productCode: "EDO32-WIDTH025",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 226,
        },
        {
            img: "ryevxior8df4yn9kkyer.jpg",
            noteRequired: false,
            description: "2-0",
            title: "2-0",
            price: null,
            value: "20",
            productCode: "EDO32-WIDTH030",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 227,
        },
        {
            img: "iifjiypgzbkhxvguz4ws.jpg",
            noteRequired: false,
            description: "",
            title: "No Sidelight",
            price: null,
            value: "SGL",
            productCode: "EFOS32-SGLTYPE005",
            qty: 1,
            meta: {},
            categoryId: 22,
            id: 228,
        },
        {
            img: "eeeif1vpks37a0a1ozdq.jpg",
            noteRequired: false,
            description: "Sidelight Only",
            title: "Sidelight Only",
            price: null,
            value: "SDLT",
            productCode: "EFOS32-SGLTYPE020",
            qty: 1,
            meta: {},
            categoryId: 22,
            id: 229,
        },
        {
            img: "allkyzio3c2cdmbmuuk8.jpg",
            noteRequired: false,
            description: "4-0 (PR 2-0)",
            title: "4-0 (PR 2-0)",
            price: null,
            value: "20",
            productCode: "EFOD32-WIDTH005",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 230,
        },
        {
            img: "u1spomwu2kufre8so36b.jpg",
            noteRequired: false,
            description: "5-0 (PR 2-6)",
            title: "5-0 (PR 2-6)",
            price: null,
            value: "26",
            productCode: "EFOD32-WIDTH010",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 231,
        },
        {
            img: "wdogv5ijdkewmymq7abz.jpg",
            noteRequired: false,
            description: "5-4 (PR 2-8)",
            title: "5-4 (PR 2-8)",
            price: null,
            value: "28",
            productCode: "EFOD32-WIDTH015",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 232,
        },
        {
            img: "frcn1upx4vl46qkr4p4h.jpg",
            noteRequired: false,
            description: "5-8 (PR 2-10)",
            title: "5-8 (PR 2-10)",
            price: null,
            value: "29",
            productCode: "EFOD32-WIDTH020",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 233,
        },
        {
            img: "vyjvbonmhvtatxvwoica.jpg",
            noteRequired: false,
            description: "6-0 (PR 3-0)",
            title: "6-0 (PR 3-0)",
            price: null,
            value: "30",
            productCode: "EFOD32-WIDTH025",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 234,
        },
        {
            img: "ukgfye44b76q8qpmxigl.jpg",
            noteRequired: false,
            description: "7-0 (PR 3-6)",
            title: "7-0 (PR 3-6)",
            price: null,
            value: "36",
            productCode: "EFOD32-WIDTH030",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 235,
        },
        {
            img: "ob2kkhfhtf8phwjoozcf.jpg",
            noteRequired: false,
            description: "Double Active",
            title: "Double Active",
            price: null,
            value: "ADBL",
            productCode: "EFOD32-DBLTYPE005",
            qty: 1,
            meta: {},
            categoryId: 23,
            id: 236,
        },
        {
            img: "r0phloffc2vn4gd8f3g4.jpg",
            noteRequired: false,
            description: "3-0",
            title: "3-0",
            price: null,
            value: "30",
            productCode: "EMFS32-WIDTH005",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 237,
        },
        {
            img: "gj8yrxpgirtyvzef1zj5.jpg",
            noteRequired: false,
            description: "x 6-8,",
            title: "6-8",
            price: 36,
            value: "68",
            productCode: "EMFS32-HEIGHT068",
            qty: 1,
            meta: {},
            categoryId: 5,
            id: 238,
        },
        {
            img: "guudiixsddkfybu2tgw7.jpg",
            noteRequired: false,
            description: "x 8-0,",
            title: "8-0",
            price: 36,
            value: "80",
            productCode: "EMFS32-HEIGHT080",
            qty: 1,
            meta: {},
            categoryId: 5,
            id: 239,
        },
        {
            img: "daddzas0ax3fcj73mwvh.jpg",
            noteRequired: false,
            description: '12"',
            title: '12" Sidelight',
            price: null,
            value: "12",
            productCode: "EDUS32-WIDTH010",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 240,
        },
        {
            img: "zwbj6kpes6vhxxfscfpq.jpg",
            noteRequired: false,
            description: "1-2",
            title: '1-2 "Special Order Only"',
            price: null,
            value: "12",
            productCode: "EDUS32-WIDTH85",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 241,
        },
        {
            img: "tbk4jhismrc0iycb9hjo.jpg",
            noteRequired: false,
            description: "1-0",
            title: '1-0 "Special Order Only"',
            price: null,
            value: "10",
            productCode: "EDUS32-WIDTH90",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 242,
        },
        {
            img: "ryevxior8df4yn9kkyer.jpg",
            noteRequired: false,
            description: "2-0",
            title: "2-0",
            price: null,
            value: "20",
            productCode: "EDUS32-WIDTH020",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 243,
        },
        {
            img: "qtxszg4tai0m76b3q1gv.jpg",
            noteRequired: false,
            description: "2-4",
            title: "2-4",
            price: null,
            value: "24",
            productCode: "EDUS32-WIDTH024",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 244,
        },
        {
            img: "v55cvt73wyxgtlmy39mh.jpg",
            noteRequired: false,
            description: "2-6",
            title: "2-6",
            price: null,
            value: "26",
            productCode: "EDUS32-WIDTH026",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 245,
        },
        {
            img: "ktmq4qeajwqgnpvbtt3m.jpg",
            noteRequired: false,
            description: "2-8",
            title: "2-8",
            price: null,
            value: "28",
            productCode: "EDUS32-WIDTH028",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 246,
        },
        {
            img: "ucyksf2ek0idnutv9ra6.jpg",
            noteRequired: false,
            description: "2-10",
            title: "2-10",
            price: null,
            value: "29",
            productCode: "EDUS32-WIDTH029",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 247,
        },
        {
            img: "r0phloffc2vn4gd8f3g4.jpg",
            noteRequired: false,
            description: "3-0",
            title: "3-0",
            price: null,
            value: "30",
            productCode: "EDUS32-WIDTH030",
            qty: 1,
            meta: {},
            categoryId: 3,
            id: 248,
        },
        {
            img: "gj8yrxpgirtyvzef1zj5.jpg",
            noteRequired: false,
            description: "x 6-8,",
            title: "6-8",
            price: null,
            value: "68",
            productCode: "EDUS32-HEIGHT068",
            qty: 1,
            meta: {},
            categoryId: 5,
            id: 249,
        },
        {
            img: "hktghwpixddhpfamnw1s.jpg",
            noteRequired: false,
            description: "x 7-0,",
            title: "7-0",
            price: null,
            value: "70",
            productCode: "EDUS32-HEIGHT070",
            qty: 1,
            meta: {},
            categoryId: 5,
            id: 250,
        },
        {
            img: "guudiixsddkfybu2tgw7.jpg",
            noteRequired: false,
            description: "x 8-0,",
            title: "8-0",
            price: null,
            value: "80",
            productCode: "EDUS32-HEIGHT080",
            qty: 1,
            meta: {},
            categoryId: 5,
            id: 251,
        },
        {
            img: "dqpxywgbe16vpwyl8cuq.jpg",
            noteRequired: false,
            description: "LH",
            title: "[LH] Left Hand",
            price: null,
            value: "LH",
            productCode: "EDUS32-HAND005",
            qty: 1,
            meta: {},
            categoryId: 6,
            id: 252,
        },
        {
            img: "mesuhjl6zugbg82tvbco.jpg",
            noteRequired: false,
            description: "RH",
            title: "[RH] Right Hand",
            price: null,
            value: "RH",
            productCode: "EDUS32-HAND010",
            qty: 1,
            meta: {},
            categoryId: 6,
            id: 253,
        },
        {
            img: "lb2zs0xoawfzg69aei9z.jpg",
            noteRequired: false,
            description: "FIXED,",
            title: "Fixed Unit",
            price: null,
            value: "FX",
            productCode: "EDUS32-HAND015",
            qty: 1,
            meta: {},
            categoryId: 6,
            id: 254,
        },
        {
            img: "xth1ythjff7d0ct59kel.jpg",
            noteRequired: false,
            description: "I/S,",
            title: "Inswing",
            price: null,
            value: "IS",
            productCode: "EDUS32-SWING005",
            qty: 1,
            meta: {},
            id: 255,
        },
        {
            img: "jsnhnqacctdgjnit80fq.jpg",
            noteRequired: false,
            description: "O/S,",
            title: "Outswing",
            price: null,
            value: "OS",
            productCode: "EDUS32-SWING010",
            qty: 1,
            meta: {},
            categoryId: 24,
            id: 256,
        },
        {
            img: "ngilyfpckm6l2ncvtufo.png",
            noteRequired: false,
            description: "DBL BORE,",
            title: "Double Bore",
            price: null,
            value: "DB",
            productCode: "EDUS32-BORE005",
            qty: 1,
            meta: {},
            categoryId: 7,
            id: 257,
        },
        {
            img: "y7el6eswux4lyvwav7uw.png",
            noteRequired: false,
            description: "SB,",
            title: "Single Bore",
            price: null,
            value: "SB",
            productCode: "EDUS32-BORE010",
            qty: 1,
            meta: {},
            categoryId: 7,
            id: 258,
        },
        {
            img: "dkpw6ghhgcyihhbcnzud.jpg",
            noteRequired: false,
            description: "NO BORE,",
            title: "No Bore",
            price: null,
            value: "NB",
            productCode: "EDUS32-BORE015",
            qty: 1,
            meta: {},
            categoryId: 7,
            id: 259,
        },
        {
            img: "htp52udjmnnowwqdno3l.jpg",
            noteRequired: false,
            description: "",
            title: "Door w/Glass",
            price: null,
            value: "YES",
            productCode: "EDUS32-DRGLASSY/N005",
            qty: 1,
            meta: {},
            id: 260,
        },
        {
            img: "t8te0m4rapdwxwtpihub.jpg",
            noteRequired: false,
            description: "",
            title: "Panel Door No Glass",
            price: null,
            value: "NO",
            productCode: "EDUS32-DRGLASSY/N010",
            qty: 1,
            meta: {},
            categoryId: 25,
            id: 261,
        },
        {
            img: "sgdjpee2moiehumcc6j7.jpg",
            noteRequired: false,
            description: "",
            title: "Door w/Open Cutout",
            price: null,
            value: "OPEN",
            productCode: "EDUS32-DRGLASSY/N015",
            qty: 1,
            meta: {},
            categoryId: 25,
            id: 262,
        },
        {
            img: "ryhaqtol67bgav4z4o11.jpg",
            noteRequired: false,
            description: "",
            title: "FullView Glass",
            price: null,
            value: "2264",
            productCode: "EDUS32-DOORVIEW005",
            qty: 1,
            meta: {},
            id: 263,
        },
        {
            img: "aurnydtpd2mmdv3xflwu.jpg",
            noteRequired: false,
            description: "",
            title: "1/2View Glass",
            price: null,
            value: "2236",
            productCode: "EDUS32-DOORVIEW025",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 264,
        },
        {
            img: "dxsfiwanqy4nfp9jrl2e.jpg",
            noteRequired: false,
            description: "",
            title: "Louver",
            price: null,
            value: "LVR",
            productCode: "EDUS32-DOORVIEW045",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 265,
        },
        {
            img: "p1pdp1axbxh4rr7ctcbr.jpg",
            noteRequired: false,
            description: "",
            title: "Vent Lights",
            price: null,
            value: "VENT",
            productCode: "EDUS32-DOORVIEW050",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 266,
        },
        {
            img: "fzw8vkuubn9jhnvjo1il.jpg",
            noteRequired: false,
            description: "",
            title: "Spotlight Glass",
            price: null,
            value: "SPOT",
            productCode: "EDUS32-DOORVIEW055",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 267,
        },
        {
            img: "yuzsnh93jdmxbthnviox.jpg",
            noteRequired: false,
            description: "",
            title: "Panel Door No Glass",
            price: null,
            value: "PNL",
            productCode: "EDUS32-DOORVIEW085",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 268,
        },
        {
            img: "ryhaqtol67bgav4z4o11.jpg",
            noteRequired: false,
            description: "",
            title: "FullView Glass",
            price: null,
            value: "2264",
            productCode: "EDUS32-DOORVIEW005",
            qty: 1,
            meta: {},
            categoryId: 26,
            id: 269,
        },
        {
            img: "vs61uqrhab4yqceslts0.jpg",
            noteRequired: false,
            description: "",
            title: "Steel",
            price: null,
            value: "STL",
            productCode: "EDUS32-DOORTYPE005",
            qty: 1,
            meta: {},
            categoryId: 1,
            id: 270,
        },
        {
            img: "e92sgfseutmrmsygjvce.jpg",
            noteRequired: false,
            description: "",
            title: "Fiberglass",
            price: null,
            value: "FG",
            productCode: "EDUS32-DOORTYPE010",
            qty: 1,
            meta: {},
            categoryId: 1,
            id: 271,
        },
        {
            img: "gnvvtpjurdmayvbdfvct.jpg",
            noteRequired: false,
            description: "STL",
            title: "Steel",
            price: null,
            value: "STL",
            productCode: "EDUS32-DOORSPECIES050",
            qty: 1,
            meta: {},
            id: 272,
        },
        {
            img: "zyntj3jxzybxuoiuntzi.jpg",
            noteRequired: false,
            description: "",
            title: "Non-Impact Door",
            price: null,
            value: "NO",
            productCode: "EDUS32-DOORIMPACT005",
            qty: 1,
            meta: {},
            id: 273,
        },
        {
            noteRequired: false,
            description: "Flush,",
            title: "2-0X6-8 STL FLUSH NB",
            price: 345,
            value: "FLUSH",
            productCode: "STLFL20",
            qty: 1,
            meta: {},
            categoryId: 8,
            id: 274,
        },
        {
            img: "h2rbjtrgxkshln0oyqr3.png",
            noteRequired: false,
            description: "",
            title: "Clear Glass",
            price: null,
            value: "CLR",
            productCode: "EDUS32-GLASSTYPE005",
            qty: 1,
            meta: {},
            id: 275,
        },
        {
            img: "i3pfu5xtdstcm5omppgt.jpg",
            noteRequired: false,
            description: "",
            title: "Raise Lower & Tilt Blinds (RLT)",
            price: null,
            value: "RLT",
            productCode: "EDUS32-GLASSTYPE010",
            qty: 1,
            meta: {},
            categoryId: 29,
            id: 276,
        },
        {
            img: "spuobblcbse9orqr3wpg.jpg",
            noteRequired: false,
            description: "",
            title: "Textured Glass",
            price: null,
            value: "TXT",
            productCode: "EDUS32-GLASSTYPE020",
            qty: 1,
            meta: {},
            categoryId: 29,
            id: 277,
        },
        {
            img: "vkcr69ujh4jbeveb9wuy.png",
            noteRequired: false,
            description: "",
            title: "Grids Between Glass (GBG)",
            price: null,
            value: "GBG",
            productCode: "EDUS32-GLASSTYPE025",
            qty: 1,
            meta: {},
            categoryId: 29,
            id: 278,
        },
        {
            img: "h5naqex97od5htzpmc9w.jpg",
            noteRequired: false,
            description: "",
            title: "Louver",
            price: null,
            value: "LVR",
            productCode: "EDUS32-GLASSTYPE045",
            qty: 1,
            meta: {},
            categoryId: 29,
            id: 279,
        },
        {
            img: "h2rbjtrgxkshln0oyqr3.png",
            noteRequired: false,
            description: "",
            title: "Clear Glass",
            price: null,
            value: "CLR",
            productCode: "EDUS32-GLASSTYPE005",
            qty: 1,
            meta: {},
            categoryId: 29,
            id: 280,
        },
        {
            img: "xzm1vym726dqlfru8xcb.jpg",
            noteRequired: false,
            description: "IMPACT GLASS",
            title: "Impact Glass",
            price: null,
            value: "YES",
            productCode: "EDUS32-GLASSIMP010",
            qty: 1,
            meta: {},
            id: 281,
        },
        {
            img: "q1rtoetus1xlzciltuam.jpg",
            noteRequired: false,
            description: "",
            title: "Insert",
            price: null,
            value: "INS",
            productCode: "EDUS32-OPENCUTOUT005",
            qty: 1,
            meta: {},
            id: 282,
        },
        {
            noteRequired: false,
            description: "1Lt IG IMP Wht FL-Frm",
            title: "1464 1LT IG IMP WHITE FLAT FRM INSERT",
            price: 825,
            value: "INSERT",
            productCode: "1464I1LF",
            qty: 0,
            meta: {},
            id: 283,
        },
        {
            noteRequired: false,
            description: "1Lt Low-E IMP Wht FL-Frm",
            title: "1464 1LT LOW-E IMP WHITE FLAT FRM INSERT",
            price: 907,
            value: "INSERT",
            productCode: "1464I1LLEF",
            qty: 0,
            meta: {},
            categoryId: 32,
            id: 284,
        },
        {
            noteRequired: false,
            description: "IG IMP Wht RLT Wht FL-Frm",
            title: "1464 1LT WHT RLT BLINDS IG IMP WHITE FLAT FRM INSERT",
            price: 1446,
            value: "INSERT",
            productCode: "1464I1LRLTF",
            qty: 0,
            meta: {},
            categoryId: 32,
            id: 285,
        },
        {
            img: "iivarp0rouknx9vwzpbp.jpg",
            noteRequired: false,
            description: "",
            title: "Shop Applied Custom SDL",
            price: null,
            value: "CSDL",
            productCode: "EDUS32-CUSTOMSDL005",
            qty: 1,
            meta: {},
            id: 286,
        },
        {
            img: "dpuvibjovdadhan08guu.jpg",
            noteRequired: false,
            description: "",
            title: "No Custom SDL",
            price: null,
            value: "NONE",
            productCode: "EDUS32-CUSTOMSDL010",
            qty: 1,
            meta: {},
            categoryId: 33,
            id: 287,
        },
        {
            img: "ncachntmrmjkpz9vmyus.jpg",
            noteRequired: false,
            description: "",
            title: "No Sidelight",
            price: null,
            value: "NOSDLT",
            productCode: "EDUS32-SDLTWIDTH099",
            qty: 1,
            meta: {},
            id: 288,
        },
        {
            img: "s7aj4t6niqsmfvmjwvww.jpg",
            noteRequired: false,
            description: '4-9/16"',
            title: '4-9/16" Jamb Depth',
            price: null,
            value: "4916",
            productCode: "EDUS32-JAMBDEPTH005",
            qty: 1,
            meta: {},
            id: 289,
        },
        {
            img: "pceikjdjwuksivcx7zdk.jpg",
            noteRequired: false,
            description: '4-7/8"',
            title: '4-7/8" Jamb Depth',
            price: null,
            value: "478",
            productCode: "EDUS32-JAMBDEPTH010",
            qty: 1,
            meta: {},
            categoryId: 35,
            id: 290,
        },
        {
            img: "jqhisdzldwe7wcvaajsm.jpg",
            noteRequired: false,
            description: '5-1/4"',
            title: '5-1/4" Jamb Depth',
            price: null,
            value: "514",
            productCode: "EDUS32-JAMBDEPTH015",
            qty: 1,
            meta: {},
            categoryId: 35,
            id: 291,
        },
        {
            img: "eq2bmbwsvsankjb3us0s.jpg",
            noteRequired: false,
            description: '6-9/16"',
            title: '6-9/16" Jamb Depth',
            price: null,
            value: "6916",
            productCode: "EDUS32-JAMBDEPTH020",
            qty: 1,
            meta: {},
            categoryId: 35,
            id: 292,
        },
        {
            img: "d5zprin3cgotv4za0skg.jpg",
            noteRequired: false,
            description: '7-1/4"',
            title: '7-1/4" Jamb Depth',
            price: null,
            value: "714",
            productCode: "EDUS32-JAMBDEPTH025",
            qty: 1,
            meta: {},
            categoryId: 35,
            id: 293,
        },
        {
            img: "m10nh17gdnzkx56qhepa.jpg",
            noteRequired: false,
            description: '9-1/4"',
            title: '9-1/4" Jamb Depth',
            price: null,
            value: "914",
            productCode: "EDUS32-JAMBDEPTH030",
            qty: 1,
            meta: {},
            categoryId: 35,
            id: 294,
        },
        {
            img: "ihnpagx3sgxdhyyyb5ph.jpg",
            noteRequired: false,
            description: "Mill",
            title: "Mill Finish",
            price: null,
            value: "MF",
            productCode: "EDUS32-SILLFINISH005",
            qty: 1,
            meta: {},
            id: 295,
        },
        {
            img: "hxnivfjlc0azmhanrq2v.jpg",
            noteRequired: false,
            description: "**NO SILL**",
            title: "No Sill",
            price: null,
            value: "NONE",
            productCode: "EDUS32-SILLFINISH015",
            qty: 1,
            meta: {},
            categoryId: 36,
            id: 296,
        },
        {
            img: "mp2exmmlnaiwrf1pmbna.jpg",
            noteRequired: false,
            description: "Adj Sill,",
            title: "Adjustable Sill",
            price: null,
            value: "ADJ",
            productCode: "EDUS32-SILLTYPE005",
            qty: 1,
            meta: {},
            id: 297,
        },
        {
            img: "ejveamrqhfgdsbufzcsz.jpg",
            noteRequired: false,
            description: "Prm Jamb,",
            title: "Primed Jamb",
            price: null,
            value: "PRM",
            productCode: "EDUS32-JMBSPECIES005",
            qty: 1,
            meta: {},
            categoryId: 10,
            id: 298,
        },
        {
            img: "nz8ifqjwfsdewqoq2vem.jpg",
            noteRequired: false,
            description: "FS Jamb,",
            title: "FrameSaver Jamb",
            price: null,
            value: "FS",
            productCode: "EDUS32-JMBSPECIES010",
            qty: 1,
            meta: {},
            categoryId: 10,
            id: 299,
        },
        {
            img: "kazbjxa8jit0vlvyjrzx.jpg",
            noteRequired: false,
            description: "Prm Comp Jamb,",
            title: "Primed Composite Jamb",
            price: null,
            value: "PRMCOMP",
            productCode: "EDUS32-JMBSPECIES015",
            qty: 1,
            meta: {},
            categoryId: 10,
            id: 300,
        },
        {
            img: "y9ahhinhcj8x6zoirxsb.jpg",
            noteRequired: false,
            description: "TXT Comp Jamb,",
            title: "Textured Composite Jamb",
            price: null,
            value: "TXTCOMP",
            productCode: "EDUS32-JMBSPECIES020",
            qty: 1,
            meta: {},
            categoryId: 10,
            id: 301,
        },
        {
            img: "abitccfum9tk5eovhjhw.jpg",
            noteRequired: false,
            description: "PR 4-9/16 X 6/8 PRIMED FJ SGL",
            title: "PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF JAMB",
            price: 52.25,
            value: "LEG",
            productCode: "JMBKPR49668P",
            qty: 1,
            meta: {},
            id: 302,
        },
        {
            img: "abitccfum9tk5eovhjhw.jpg",
            noteRequired: false,
            description: "PR 4-9/16 X 6/8 PRIMED FJ SGL",
            title: "PR 4-9/16 X 6/8 PRIMED FJ SGL RBT KERF 20MIN JAMB",
            price: 57.75,
            value: "LEG20M",
            productCode: "JMBKPR49668XP",
            qty: 1,
            meta: {},
            categoryId: 38,
            id: 303,
        },
        {
            img: "uf9nboeln9wizejrbqyf.jpg",
            noteRequired: false,
            description: "",
            title: "Do Not Rip Jamb",
            price: null,
            value: "NORIP",
            productCode: "EDUS32-JMBRIP005",
            qty: 1,
            meta: {},
            categoryId: 13,
            id: 304,
        },
        {
            img: "eqjqdnrlxo1muqbi3ydh.svg",
            noteRequired: true,
            description: "**** RIP JAMB ****",
            title: "Rip Jamb to Custom Size",
            price: 12,
            value: "RIP",
            productCode: "EDUS32-JMBRIP010",
            qty: 1,
            meta: {},
            categoryId: 13,
            id: 305,
        },
        {
            img: "cz9nzenoldqyf8l5anej.jpg",
            noteRequired: false,
            description: "WHT W/S,",
            title: "White Weatherstrip",
            price: null,
            value: "WHT",
            productCode: "EDUS32-WSTRIPCOLOR005",
            qty: 1,
            meta: {},
            id: 306,
        },
        {
            img: "f8phmouicmpqkuhjcpcx.jpg",
            noteRequired: false,
            description: "BRZ W/S,",
            title: "Bronze Weatherstrip",
            price: null,
            value: "BRZ",
            productCode: "EDUS32-WSTRIPCOLOR010",
            qty: 1,
            meta: {},
            categoryId: 39,
            id: 307,
        },
        {
            img: "xtpllrld3ruxqbof8xu1.jpg",
            noteRequired: false,
            description: "",
            title: "Standard Hinges",
            price: null,
            value: "STD",
            productCode: "EDUS32-HINGETYPE005",
            qty: 1,
            meta: {},
            categoryId: 21,
            id: 308,
        },
        {
            img: "ifk8eeymfliwezyv0iah.jpg",
            noteRequired: false,
            description: "",
            title: "Spring Hinges",
            price: null,
            value: "SPR",
            productCode: "EDUS32-HINGETYPE015",
            qty: 1,
            meta: {},
            categoryId: 21,
            id: 309,
        },
        {
            img: "w4dimtfk9a96scgwiudo.jpg",
            noteRequired: false,
            description: "",
            title: "Ball Bearing Hinges",
            price: null,
            value: "BB",
            productCode: "EDUS32-HINGETYPE020",
            qty: 1,
            meta: {},
            categoryId: 21,
            id: 310,
        },
        {
            img: "uk0huexf3jis42xh2kr9.jpg",
            noteRequired: false,
            description: "STD US19 Matte Black Hinge,",
            title: "US19---Matte Black",
            price: null,
            value: "US19",
            productCode: "EDUS32-HNGFINISH065",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 311,
        },
        {
            img: "djew8azc6dko1w0k7rhr.jpg",
            noteRequired: false,
            description: "STD US2D Dull Brass",
            title: "US2D---Dull Brass",
            price: null,
            value: "US2D",
            productCode: "EDUS32-HNGFINISH070",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 312,
        },
        {
            img: "duwi0irvl8hsr0inpuie.jpg",
            noteRequired: false,
            description: "STD US5A Antique Brass",
            title: "US5A---Antique Brass",
            price: null,
            value: "US5A",
            productCode: "EDUS32-HNGFINISH075",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 313,
        },
        {
            img: "xivgxnoy1d0pqqiz4ey6.jpg",
            noteRequired: false,
            description: "STD US10B Oil Rubbed Brz",
            title: "US10B---Oil Rubbed Bronze",
            price: null,
            value: "US10B",
            productCode: "EDUS32-HNGFINISH080",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 314,
        },
        {
            img: "wznrn7lrcqbmzgc5yzkj.jpg",
            noteRequired: false,
            description: "STD USP Primed",
            title: "USP---Primed",
            price: null,
            value: "USP",
            productCode: "EDUS32-HNGFINISH085",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 315,
        },
        {
            img: "dtzhml9mltylihwisblm.jpg",
            noteRequired: false,
            description: "STD US15 Satin Nickel",
            title: "US15---Satin Nickel",
            price: null,
            value: "US15",
            productCode: "EDUS32-HNGFINISH090",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 316,
        },
        {
            img: "k1ownr7jkwtisbbf03z8.jpg",
            noteRequired: false,
            description: "STD US26 Bright Chrome",
            title: "US26---Bright Chrome",
            price: null,
            value: "US26",
            productCode: "EDUS32-HNGFINISH095",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 317,
        },
        {
            img: "exvurwrorrqkeowefnea.jpg",
            noteRequired: false,
            description: "STD US26D Brushed Chrome",
            title: "US26D---Brushed Chrome",
            price: null,
            value: "US26D",
            productCode: "EDUS32-HNGFINISH100",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 318,
        },
        {
            img: "wo3nidpxirjvsslijixm.jpg",
            noteRequired: false,
            description: "STD US32D Stainless Steel",
            title: "US32D---Stainless Steel",
            price: null,
            value: "US32D",
            productCode: "EDUS32-HNGFINISH105",
            qty: 1,
            meta: {},
            categoryId: 14,
            id: 319,
        },
        {
            img: "pyhq1knmex25lcg5w7xt.jpg",
            noteRequired: false,
            description: "Prm",
            title: "Primed Exterior Trim",
            price: null,
            value: "PRM",
            productCode: "EDUS32-BMSPECIES005",
            qty: 1,
            meta: {},
            id: 320,
        },
        {
            img: "rvlmkk4soaizfkj6anxw.jpg",
            noteRequired: false,
            description: "Prm Comp",
            title: "White PVC Exterior Trim",
            price: null,
            value: "WHTPVC",
            productCode: "EDUS32-BMSPECIES010",
            qty: 1,
            meta: {},
            categoryId: 40,
            id: 321,
        },
        {
            img: "ys5rs5nqegpv1zmjgtdb.jpg",
            noteRequired: false,
            description: "TXT Comp",
            title: "Stainable PVC Exterior Trim",
            price: null,
            value: "STNPVC",
            productCode: "EDUS32-BMSPECIES015",
            qty: 1,
            meta: {},
            categoryId: 40,
            id: 322,
        },
        {
            img: "tndzb5e5rpaovhd4jouk.jpg",
            noteRequired: false,
            description: "No Trim",
            title: "No Exterior Trim",
            price: null,
            value: "NONE",
            productCode: "EDUS32-BMSPECIES099",
            qty: 1,
            meta: {},
            categoryId: 40,
            id: 323,
        },
        {
            img: "doz3jwpbaakknasrje1l.jpg",
            noteRequired: false,
            description: "176 BM,",
            title: "PC 6/8 PRIMED FJ WM176 BRICKMOULD",
            price: 5.22,
            value: "EXTTRIM",
            productCode: "MOLBMPM17670",
            qty: 2,
            meta: {},
            id: 324,
        },
        {
            img: "ontzjigjplar10kyt3il.jpg",
            noteRequired: false,
            description: "",
            title: "No Cutdown",
            price: null,
            value: "NO",
            productCode: "EDUS32-CUTDOWNHT005",
            qty: 1,
            meta: {},
            categoryId: 16,
            id: 325,
        },
        {
            img: "ob0ya6mlulmqfg7m3nsm.jpg",
            noteRequired: false,
            description: "",
            title: "No Cutdown",
            price: null,
            value: "NO",
            productCode: "EDUS32-CUTDOWNWT005",
            qty: 1,
            meta: {},
            id: 326,
        },
        {
            img: "cchuopwyxai8ejbm1q6l.svg",
            noteRequired: true,
            description: "*** Cut Down Width ***",
            title: "Cutdown Width",
            price: 300,
            value: "YES",
            productCode: "EDUS32-CUTDOWNWT010",
            qty: 1,
            meta: {},
            categoryId: 43,
            id: 327,
        },
        {
            img: "pwppded0puyq4nuxngyd.jpg",
            noteRequired: false,
            description: "",
            title: "None",
            price: null,
            value: "NONE",
            productCode: "EDUS32-FIRELBLDR005",
            qty: 1,
            meta: {},
            id: 328,
        },
        {
            img: "aqa0cypi9jacqkmmmdp8.jpg",
            noteRequired: false,
            description: "",
            title: "None",
            price: null,
            value: "NONE",
            productCode: "EDUS32-FIRELBLJMB005",
            qty: 1,
            meta: {},
            id: 329,
        },
    ],
};
